# Generated by Django 6.0.5 on 2026-05-12 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrateur',
            fields=[
                ('emailadmin', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mot_pass', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='annonce',
            fields=[
                ('idannonce', models.AutoField(primary_key=True, serialize=False)),
                ('objets', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='enseignant',
            fields=[
                ('mail', models.CharField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('specialite', models.CharField(choices=[('ANA', 'analyse'), ('ALG', 'algebre'), ('Ph', 'Physique'), ('Chi', 'Chimie'), ('Bio', 'Biologie')])),
                ('mot_pass', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('numero_carte', models.CharField(max_length=50, null=True)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=50, null=True)),
                ('date_naiss', models.DateField(auto_now_add=True, null=True)),
                ('genre', models.CharField(max_length=50, null=True)),
                ('site_mat', models.CharField(max_length=50, null=True)),
                ('tel', models.IntegerField(null=True)),
                ('mot_pass', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_module', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reponsable',
            fields=[
                ('mail', models.CharField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('specialite', models.CharField(choices=[('ANA', 'analyse'), ('ALG', 'algebre'), ('Ph', 'Physique'), ('Chi', 'Chimie'), ('Bio', 'Biologie')])),
                ('statut', models.CharField(choices=[('prof', 'professeur simple'), ('ress', 'professeur responsable')])),
                ('mot_pass', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='classe',
            fields=[
                ('idclasse', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D1', 'Doctorat1'), ('D2', 'Doctorat2')])),
                ('cycle', models.CharField(choices=[('C1', 'premier cycle'), ('C2', 'deuxieme cycle'), ('C3', 'troisieme cycle')], null=True)),
                ('emailadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.administrateur')),
            ],
        ),
    ]
