# Generated by Django 6.0.5 on 2026-05-12 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='emailadmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.administrateur'),
        ),
    ]
