# Generated by Django 6.0.5 on 2026-05-12 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0002_enseignant_emailadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='mail',
            new_name='mailens',
        ),
        migrations.CreateModel(
            name='consulterAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idannonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.annonce')),
                ('mailens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.enseignant')),
                ('numero_carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.etudiant')),
            ],
        ),
    ]
