# Generated by Django 6.0.5 on 2026-05-12 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0003_rename_mail_enseignant_mailens_consulterannonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='mailens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.enseignant'),
        ),
    ]
