# Generated by Django 6.0.5 on 2026-05-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0004_annonce_mailens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ressource',
            fields=[
                ('idressurce', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.classe')),
                ('mailens', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.enseignant')),
            ],
        ),
    ]
