# Generated by Django 6.0.5 on 2026-05-12 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0005_ressource'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='idclasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.classe'),
        ),
    ]
