# Generated by Django 6.0.5 on 2026-05-12 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0006_etudiant_idclasse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='idressurce',
            new_name='idressource',
        ),
        migrations.CreateModel(
            name='consulterRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('idressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.ressource')),
                ('numero_carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.etudiant')),
            ],
        ),
    ]
