# Generated by Django 6.0.5 on 2026-05-12 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0007_rename_idressurce_ressource_idressource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='id',
            new_name='idmodule',
        ),
        migrations.RenameField(
            model_name='reponsable',
            old_name='mail',
            new_name='mailesp',
        ),
        migrations.AddField(
            model_name='module',
            name='coefficient',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='durésemaine',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='emailresp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.reponsable'),
        ),
        migrations.CreateModel(
            name='concernerAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idannonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.annonce')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.classe')),
            ],
        ),
        migrations.CreateModel(
            name='concernerHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.enseignant')),
                ('idressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.ressource')),
                ('numero_carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.classe')),
                ('mailens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.enseignant')),
            ],
        ),
    ]
