# Generated by Django 6.0.5 on 2026-05-12 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0008_rename_id_module_idmodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponsable',
            name='emailadmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.administrateur'),
        ),
    ]
