# Generated by Django 6.0.5 on 2026-05-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0009_reponsable_emailadmin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consulterannonce',
            unique_together={('numero_carte', 'idannonce', 'mailens')},
        ),
    ]
