# Generated by Django 6.0.5 on 2026-05-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0010_alter_consulterannonce_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='cycle',
            field=models.CharField(choices=[('C1', 'premier cycle'), ('C2', 'deuxieme cycle'), ('C3', 'troisieme cycle')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D1', 'Doctorat1'), ('D2', 'Doctorat2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='concernerannonce',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='concernerhistorique',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consulterannonce',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consulterressource',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='mailens',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='specialite',
            field=models.CharField(choices=[('ANA', 'analyse'), ('ALG', 'algebre'), ('Ph', 'Physique'), ('Chi', 'Chimie'), ('Bio', 'Biologie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='coefficient',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='durésemaine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reponsable',
            name='mailesp',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reponsable',
            name='specialite',
            field=models.CharField(choices=[('ANA', 'analyse'), ('ALG', 'algebre'), ('Ph', 'Physique'), ('Chi', 'Chimie'), ('Bio', 'Biologie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reponsable',
            name='statut',
            field=models.CharField(choices=[('prof', 'professeur simple'), ('ress', 'professeur responsable')], max_length=50),
        ),
    ]
