# Generated by Django 6.0.5 on 2026-05-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0011_alter_classe_cycle_alter_classe_niveau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='site_mat',
            field=models.CharField(choices=[('celib', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf(ve)')], max_length=50, null=True),
        ),
    ]
