# Generated by Django 6.0.5 on 2026-05-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0012_alter_etudiant_genre_alter_etudiant_site_mat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='mailens',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='specialite',
            field=models.CharField(choices=[('ANA', 'analyse'), ('ALG', 'algebre'), ('Ph', 'Physique'), ('Chi', 'Chimie'), ('Bio', 'Biologie')]),
        ),
        migrations.AlterField(
            model_name='reponsable',
            name='mailesp',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
