# Generated by Django 6.0.5 on 2026-05-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0013_alter_enseignant_mailens_alter_enseignant_specialite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponsable',
            name='statut',
        ),
        migrations.AddField(
            model_name='reponsable',
            name='idclasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.classe'),
        ),
    ]
