# Generated by Django 6.0.5 on 2026-05-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0014_remove_reponsable_statut_reponsable_idclasse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponsable',
            name='idclasse',
        ),
        migrations.AddField(
            model_name='classe',
            name='emailresp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.reponsable'),
        ),
    ]
