# Generated by Django 6.0.5 on 2026-05-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0015_remove_reponsable_idclasse_classe_emailresp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='emailresp',
        ),
        migrations.AddField(
            model_name='reponsable',
            name='idclasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.classe'),
        ),
    ]
