# Generated by Django 6.0.5 on 2026-05-28 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0016_remove_classe_emailresp_reponsable_idclasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='id_classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.classe'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='fichier',
            field=models.FileField(null=True, upload_to='ressources/'),
        ),
    ]
