# Generated by Django 6.0.5 on 2026-06-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0018_module_enseignant_module_idclasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('idnote', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.FloatField(null=True)),
                ('idmodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.module')),
                ('numero_carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.etudiant')),
            ],
        ),
    ]
