# Generated by Django 6.0.5 on 2026-06-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0019_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='mailens',
        ),
        migrations.AddField(
            model_name='annonce',
            name='idclasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.classe'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='mailres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressourceSection.reponsable'),
        ),
    ]
