# Generated by Django 6.0.5 on 2026-06-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressourceSection', '0020_remove_annonce_mailens_annonce_idclasse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='objets',
            new_name='message',
        ),
    ]
